-- Миграция: добавить qty и unit в ингредиенты food_catalog
-- Запускать в Supabase SQL editor
-- Обновляет существующие строки по имени блюда

UPDATE public.food_catalog SET ingredients = '[{"name":"овсяные хлопья","category":"grain","qty":80,"unit":"г"},{"name":"молоко","category":"dairy","qty":200,"unit":"мл"},{"name":"сахар","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Овсяная каша на молоке';
UPDATE public.food_catalog SET ingredients = '[{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"молоко","category":"dairy","qty":50,"unit":"мл"},{"name":"помидоры","category":"vegetable","qty":100,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Омлет с помидорами';
UPDATE public.food_catalog SET ingredients = '[{"name":"творог","category":"dairy","qty":150,"unit":"г"},{"name":"сметана","category":"dairy","qty":40,"unit":"г"},{"name":"сахар","category":"condiment","qty":10,"unit":"г"}]' WHERE name = 'Творог со сметаной';
UPDATE public.food_catalog SET ingredients = '[{"name":"гречка","category":"grain","qty":80,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Гречневая каша с маслом';
UPDATE public.food_catalog SET ingredients = '[{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"бекон","category":"meat","qty":60,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Яичница с беконом';
UPDATE public.food_catalog SET ingredients = '[{"name":"творог","category":"dairy","qty":150,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"мука пшеничная","category":"grain","qty":30,"unit":"г"},{"name":"сахар","category":"condiment","qty":15,"unit":"г"},{"name":"сметана","category":"dairy","qty":30,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"}]' WHERE name = 'Сырники со сметаной';
UPDATE public.food_catalog SET ingredients = '[{"name":"мука пшеничная","category":"grain","qty":100,"unit":"г"},{"name":"молоко","category":"dairy","qty":300,"unit":"мл"},{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"масло сливочное","category":"condiment","qty":20,"unit":"г"},{"name":"сахар","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Блины на молоке';
UPDATE public.food_catalog SET ingredients = '[{"name":"хлеб пшеничный","category":"grain","qty":80,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":15,"unit":"г"},{"name":"сыр российский","category":"dairy","qty":40,"unit":"г"}]' WHERE name = 'Бутерброд с сыром и маслом';
UPDATE public.food_catalog SET ingredients = '[{"name":"мюсли","category":"grain","qty":80,"unit":"г"},{"name":"йогурт натуральный","category":"dairy","qty":150,"unit":"мл"},{"name":"банан","category":"fruit","qty":1,"unit":"шт"}]' WHERE name = 'Мюсли с йогуртом';
UPDATE public.food_catalog SET ingredients = '[{"name":"пшено","category":"grain","qty":80,"unit":"г"},{"name":"молоко","category":"dairy","qty":200,"unit":"мл"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"сахар","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Пшённая каша на молоке';

UPDATE public.food_catalog SET ingredients = '[{"name":"фарш свиной","category":"meat","qty":80,"unit":"г"},{"name":"фарш говяжий","category":"meat","qty":80,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"хлеб белый","category":"grain","qty":30,"unit":"г"},{"name":"молоко","category":"dairy","qty":30,"unit":"мл"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Котлеты домашние';
UPDATE public.food_catalog SET ingredients = '[{"name":"куриное филе","category":"meat","qty":220,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"},{"name":"паприка","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Куриное филе запечённое';
UPDATE public.food_catalog SET ingredients = '[{"name":"говядина","category":"meat","qty":170,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":80,"unit":"г"},{"name":"морковь","category":"vegetable","qty":60,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"лавровый лист","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Говядина тушёная с луком';
UPDATE public.food_catalog SET ingredients = '[{"name":"свинина","category":"meat","qty":150,"unit":"г"},{"name":"картофель","category":"vegetable","qty":200,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"}]' WHERE name = 'Свинина с картошкой в духовке';
UPDATE public.food_catalog SET ingredients = '[{"name":"пельмени","category":"meat","qty":280,"unit":"г"},{"name":"сметана","category":"dairy","qty":40,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Пельмени со сметаной';
UPDATE public.food_catalog SET ingredients = '[{"name":"минтай","category":"meat","qty":220,"unit":"г"},{"name":"мука пшеничная","category":"grain","qty":20,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":20,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"лимон","category":"fruit","qty":0.5,"unit":"шт"}]' WHERE name = 'Рыба жареная';
UPDATE public.food_catalog SET ingredients = '[{"name":"куриные бёдра","category":"meat","qty":250,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":60,"unit":"г"},{"name":"морковь","category":"vegetable","qty":50,"unit":"г"},{"name":"томатная паста","category":"condiment","qty":20,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Куриные бёдра тушёные';
UPDATE public.food_catalog SET ingredients = '[{"name":"макароны","category":"grain","qty":100,"unit":"г"},{"name":"фарш говяжий","category":"meat","qty":120,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":60,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"томатная паста","category":"condiment","qty":20,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Макароны по-флотски';
UPDATE public.food_catalog SET ingredients = '[{"name":"лосось","category":"meat","qty":220,"unit":"г"},{"name":"лимон","category":"fruit","qty":0.5,"unit":"шт"},{"name":"масло оливковое","category":"condiment","qty":15,"unit":"мл"},{"name":"укроп","category":"vegetable","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Лосось запечённый с лимоном';
UPDATE public.food_catalog SET ingredients = '[{"name":"фарш смешанный","category":"meat","qty":150,"unit":"г"},{"name":"рис","category":"grain","qty":30,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"томатная паста","category":"condiment","qty":40,"unit":"г"},{"name":"морковь","category":"vegetable","qty":50,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Тефтели в томатном соусе';

UPDATE public.food_catalog SET ingredients = '[{"name":"гречка","category":"grain","qty":80,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Гречка варёная';
UPDATE public.food_catalog SET ingredients = '[{"name":"рис белый","category":"grain","qty":80,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Рис белый варёный';
UPDATE public.food_catalog SET ingredients = '[{"name":"картофель","category":"vegetable","qty":250,"unit":"г"},{"name":"молоко","category":"dairy","qty":80,"unit":"мл"},{"name":"масло сливочное","category":"condiment","qty":15,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Картофельное пюре';
UPDATE public.food_catalog SET ingredients = '[{"name":"макароны","category":"grain","qty":80,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Макароны варёные';
UPDATE public.food_catalog SET ingredients = '[{"name":"капуста белокочанная","category":"vegetable","qty":300,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"морковь","category":"vegetable","qty":50,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":20,"unit":"мл"},{"name":"томатная паста","category":"condiment","qty":20,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Капуста тушёная';
UPDATE public.food_catalog SET ingredients = '[{"name":"перловая крупа","category":"grain","qty":70,"unit":"г"},{"name":"масло сливочное","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Перловая каша';
UPDATE public.food_catalog SET ingredients = '[{"name":"брокколи","category":"vegetable","qty":220,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"масло оливковое","category":"condiment","qty":10,"unit":"мл"}]' WHERE name = 'Брокколи на пару';
UPDATE public.food_catalog SET ingredients = '[{"name":"кабачки","category":"vegetable","qty":250,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"морковь","category":"vegetable","qty":40,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Тушёные кабачки';
UPDATE public.food_catalog SET ingredients = '[{"name":"чечевица","category":"grain","qty":80,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":50,"unit":"г"},{"name":"морковь","category":"vegetable","qty":40,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Чечевица варёная';
UPDATE public.food_catalog SET ingredients = '[{"name":"картофель","category":"vegetable","qty":250,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"розмарин","category":"condiment","qty":1,"unit":"щепотка"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Картофель запечённый';

UPDATE public.food_catalog SET ingredients = '[{"name":"огурцы","category":"vegetable","qty":80,"unit":"г"},{"name":"помидоры","category":"vegetable","qty":80,"unit":"г"},{"name":"лук зелёный","category":"vegetable","qty":15,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Салат из огурцов и помидоров';
UPDATE public.food_catalog SET ingredients = '[{"name":"помидоры","category":"vegetable","qty":70,"unit":"г"},{"name":"огурцы","category":"vegetable","qty":50,"unit":"г"},{"name":"перец болгарский","category":"vegetable","qty":40,"unit":"г"},{"name":"лук красный","category":"vegetable","qty":20,"unit":"г"},{"name":"сыр фета","category":"dairy","qty":50,"unit":"г"},{"name":"маслины","category":"condiment","qty":20,"unit":"г"},{"name":"масло оливковое","category":"condiment","qty":15,"unit":"мл"},{"name":"орегано","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Салат греческий';
UPDATE public.food_catalog SET ingredients = '[{"name":"картофель","category":"vegetable","qty":50,"unit":"г"},{"name":"морковь","category":"vegetable","qty":30,"unit":"г"},{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"колбаса варёная","category":"meat","qty":50,"unit":"г"},{"name":"огурцы маринованные","category":"vegetable","qty":30,"unit":"г"},{"name":"горошек зелёный","category":"vegetable","qty":30,"unit":"г"},{"name":"майонез","category":"condiment","qty":40,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Салат Оливье';
UPDATE public.food_catalog SET ingredients = '[{"name":"морковь","category":"vegetable","qty":120,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"майонез","category":"condiment","qty":30,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Морковный салат с чесноком';
UPDATE public.food_catalog SET ingredients = '[{"name":"свёкла","category":"vegetable","qty":60,"unit":"г"},{"name":"картофель","category":"vegetable","qty":50,"unit":"г"},{"name":"морковь","category":"vegetable","qty":40,"unit":"г"},{"name":"огурцы маринованные","category":"vegetable","qty":30,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":20,"unit":"г"},{"name":"горошек зелёный","category":"vegetable","qty":20,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Винегрет';
UPDATE public.food_catalog SET ingredients = '[{"name":"капуста белокочанная","category":"vegetable","qty":140,"unit":"г"},{"name":"морковь","category":"vegetable","qty":40,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":15,"unit":"мл"},{"name":"уксус","category":"condiment","qty":10,"unit":"мл"},{"name":"сахар","category":"condiment","qty":5,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Салат из капусты';
UPDATE public.food_catalog SET ingredients = '[{"name":"куриное филе","category":"meat","qty":80,"unit":"г"},{"name":"салат романо","category":"vegetable","qty":60,"unit":"г"},{"name":"сыр пармезан","category":"dairy","qty":20,"unit":"г"},{"name":"сухарики","category":"grain","qty":20,"unit":"г"},{"name":"соус цезарь","category":"condiment","qty":30,"unit":"г"}]' WHERE name = 'Салат Цезарь с курицей';
UPDATE public.food_catalog SET ingredients = '[{"name":"свёкла","category":"vegetable","qty":100,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":5,"unit":"г"},{"name":"грецкие орехи","category":"other","qty":20,"unit":"г"},{"name":"майонез","category":"condiment","qty":25,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Свекольный салат с орехами';
UPDATE public.food_catalog SET ingredients = '[{"name":"тунец консервированный","category":"meat","qty":80,"unit":"г"},{"name":"помидоры","category":"vegetable","qty":50,"unit":"г"},{"name":"огурцы","category":"vegetable","qty":30,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"лук зелёный","category":"vegetable","qty":10,"unit":"г"},{"name":"майонез","category":"condiment","qty":30,"unit":"г"}]' WHERE name = 'Салат из тунца';
UPDATE public.food_catalog SET ingredients = '[{"name":"огурцы","category":"vegetable","qty":60,"unit":"г"},{"name":"помидоры","category":"vegetable","qty":60,"unit":"г"},{"name":"болгарский перец","category":"vegetable","qty":40,"unit":"г"},{"name":"зелень","category":"vegetable","qty":10,"unit":"г"},{"name":"сметана","category":"dairy","qty":25,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Дачный салат';

UPDATE public.food_catalog SET ingredients = '[{"name":"творог","category":"dairy","qty":150,"unit":"г"},{"name":"яблоко","category":"fruit","qty":0.5,"unit":"шт"},{"name":"банан","category":"fruit","qty":0.5,"unit":"шт"},{"name":"мёд","category":"condiment","qty":15,"unit":"г"}]' WHERE name = 'Творог с фруктами';
UPDATE public.food_catalog SET ingredients = '[{"name":"йогурт натуральный","category":"dairy","qty":150,"unit":"мл"},{"name":"мюсли","category":"grain","qty":50,"unit":"г"},{"name":"ягоды","category":"fruit","qty":30,"unit":"г"}]' WHERE name = 'Йогурт с мюсли';
UPDATE public.food_catalog SET ingredients = '[{"name":"яблоко","category":"fruit","qty":1,"unit":"шт"},{"name":"арахисовая паста","category":"other","qty":30,"unit":"г"}]' WHERE name = 'Яблоко с арахисовой пастой';
UPDATE public.food_catalog SET ingredients = '[{"name":"кефир","category":"dairy","qty":200,"unit":"мл"},{"name":"хлебцы","category":"grain","qty":40,"unit":"г"}]' WHERE name = 'Кефир с хлебцами';
UPDATE public.food_catalog SET ingredients = '[{"name":"банан","category":"fruit","qty":1,"unit":"шт"},{"name":"грецкие орехи","category":"other","qty":25,"unit":"г"}]' WHERE name = 'Банан с орехами';
UPDATE public.food_catalog SET ingredients = '[{"name":"творог","category":"dairy","qty":100,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"манная крупа","category":"grain","qty":20,"unit":"г"},{"name":"сахар","category":"condiment","qty":15,"unit":"г"},{"name":"сметана","category":"dairy","qty":20,"unit":"г"},{"name":"изюм","category":"fruit","qty":20,"unit":"г"}]' WHERE name = 'Творожная запеканка';
UPDATE public.food_catalog SET ingredients = '[{"name":"хлеб цельнозерновой","category":"grain","qty":60,"unit":"г"},{"name":"авокадо","category":"fruit","qty":0.5,"unit":"шт"},{"name":"лимонный сок","category":"condiment","qty":5,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Бутерброд с авокадо';
UPDATE public.food_catalog SET ingredients = '[{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Варёное яйцо';
UPDATE public.food_catalog SET ingredients = '[{"name":"яблоко","category":"fruit","qty":0.5,"unit":"шт"},{"name":"банан","category":"fruit","qty":0.5,"unit":"шт"},{"name":"апельсин","category":"fruit","qty":0.5,"unit":"шт"},{"name":"клубника","category":"fruit","qty":50,"unit":"г"},{"name":"мёд","category":"condiment","qty":10,"unit":"г"}]' WHERE name = 'Фруктовый салат';
UPDATE public.food_catalog SET ingredients = '[{"name":"сыр твёрдый","category":"dairy","qty":60,"unit":"г"},{"name":"виноград","category":"fruit","qty":50,"unit":"г"}]' WHERE name = 'Сыр с виноградом';

-- Блюда из второго seed-файла
UPDATE public.food_catalog SET ingredients = '[{"name":"мука пшеничная","category":"grain","qty":60,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"кефир","category":"dairy","qty":150,"unit":"мл"},{"name":"ветчина","category":"meat","qty":60,"unit":"г"},{"name":"сыр твёрдый","category":"dairy","qty":40,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"разрыхлитель","category":"condiment","qty":5,"unit":"г"}]' WHERE name = 'Оладьи с ветчиной и сыром';
UPDATE public.food_catalog SET ingredients = '[{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"помидоры","category":"vegetable","qty":80,"unit":"г"},{"name":"ветчина","category":"meat","qty":60,"unit":"г"},{"name":"масло сливочное","category":"dairy","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"зелень","category":"vegetable","qty":10,"unit":"г"}]' WHERE name = 'Яичница с помидорами и ветчиной';
UPDATE public.food_catalog SET ingredients = '[{"name":"творог 9%","category":"dairy","qty":150,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"мука пшеничная","category":"grain","qty":30,"unit":"г"},{"name":"сахар","category":"condiment","qty":10,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"сгущёное молоко","category":"dairy","qty":30,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"}]' WHERE name = 'Сырники со сгущёнкой';
UPDATE public.food_catalog SET ingredients = '[{"name":"овсяные хлопья","category":"grain","qty":80,"unit":"г"},{"name":"молоко","category":"dairy","qty":250,"unit":"мл"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"сыр твёрдый","category":"dairy","qty":30,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"масло сливочное","category":"dairy","qty":10,"unit":"г"}]' WHERE name = 'Овсянка с сыром и яйцом';
UPDATE public.food_catalog SET ingredients = '[{"name":"хлеб тостовый","category":"grain","qty":60,"unit":"г"},{"name":"колбаса варёная","category":"meat","qty":50,"unit":"г"},{"name":"сыр твёрдый","category":"dairy","qty":30,"unit":"г"},{"name":"масло сливочное","category":"dairy","qty":10,"unit":"г"}]' WHERE name = 'Горячий бутерброд: колбаса + сыр';
UPDATE public.food_catalog SET ingredients = '[{"name":"батат","category":"vegetable","qty":150,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"мука рисовая","category":"grain","qty":40,"unit":"г"},{"name":"сметана","category":"dairy","qty":40,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"корица","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Оладьи из батата со сметаной';
UPDATE public.food_catalog SET ingredients = '[{"name":"яйца","category":"dairy","qty":2,"unit":"шт"},{"name":"авокадо","category":"fruit","qty":1,"unit":"шт"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"},{"name":"лимонный сок","category":"condiment","qty":5,"unit":"мл"}]' WHERE name = 'Блин из яйца с авокадо';
UPDATE public.food_catalog SET ingredients = '[{"name":"говядина","category":"meat","qty":170,"unit":"г"},{"name":"морковь","category":"vegetable","qty":60,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":60,"unit":"г"},{"name":"томатная паста","category":"condiment","qty":20,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"лавровый лист","category":"condiment","qty":1,"unit":"щепотка"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Тушёная говядина с овощами';
UPDATE public.food_catalog SET ingredients = '[{"name":"филе индейки","category":"meat","qty":220,"unit":"г"},{"name":"соевый соус","category":"condiment","qty":20,"unit":"мл"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"оливковое масло","category":"condiment","qty":15,"unit":"мл"},{"name":"тимьян","category":"condiment","qty":1,"unit":"щепотка"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Стейк индейки';
UPDATE public.food_catalog SET ingredients = '[{"name":"лосось","category":"meat","qty":200,"unit":"г"},{"name":"лимон","category":"fruit","qty":0.5,"unit":"шт"},{"name":"оливковое масло","category":"condiment","qty":15,"unit":"мл"},{"name":"укроп","category":"vegetable","qty":10,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":5,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Запечённый лосось';
UPDATE public.food_catalog SET ingredients = '[{"name":"фарш из индейки","category":"meat","qty":160,"unit":"г"},{"name":"цукини","category":"vegetable","qty":80,"unit":"г"},{"name":"лук репчатый","category":"vegetable","qty":40,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Биточки из индейки с цукини';
UPDATE public.food_catalog SET ingredients = '[{"name":"куриное филе","category":"meat","qty":130,"unit":"г"},{"name":"батат","category":"vegetable","qty":130,"unit":"г"},{"name":"оливковое масло","category":"condiment","qty":15,"unit":"мл"},{"name":"чеснок","category":"vegetable","qty":10,"unit":"г"},{"name":"паприка","category":"condiment","qty":1,"unit":"щепотка"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Запечённый батат с курицей';
UPDATE public.food_catalog SET ingredients = '[{"name":"тунец консервированный","category":"meat","qty":100,"unit":"г"},{"name":"яйца","category":"dairy","qty":1,"unit":"шт"},{"name":"мука овсяная","category":"grain","qty":40,"unit":"г"},{"name":"лук зелёный","category":"vegetable","qty":20,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"перец","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Лепёшка из тунца';
UPDATE public.food_catalog SET ingredients = '[{"name":"рис","category":"grain","qty":70,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Рис варёный';
UPDATE public.food_catalog SET ingredients = '[{"name":"картофель","category":"vegetable","qty":250,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Картофель варёный';
UPDATE public.food_catalog SET ingredients = '[{"name":"булгур","category":"grain","qty":70,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Булгур варёный';
UPDATE public.food_catalog SET ingredients = '[{"name":"огурцы","category":"vegetable","qty":70,"unit":"г"},{"name":"помидоры","category":"vegetable","qty":70,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Овощной салат (огурец + помидор)';
UPDATE public.food_catalog SET ingredients = '[{"name":"помидоры","category":"vegetable","qty":50,"unit":"г"},{"name":"огурцы","category":"vegetable","qty":40,"unit":"г"},{"name":"перец болгарский","category":"vegetable","qty":30,"unit":"г"},{"name":"маслины","category":"other","qty":20,"unit":"г"},{"name":"сыр фета","category":"dairy","qty":40,"unit":"г"},{"name":"оливковое масло","category":"condiment","qty":15,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Греческий салат';
UPDATE public.food_catalog SET ingredients = '[{"name":"капуста белокочанная","category":"vegetable","qty":110,"unit":"г"},{"name":"морковь","category":"vegetable","qty":30,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"},{"name":"уксус","category":"condiment","qty":5,"unit":"мл"}]' WHERE name = 'Капустный салат';
UPDATE public.food_catalog SET ingredients = '[{"name":"морковь","category":"vegetable","qty":100,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"чеснок","category":"vegetable","qty":5,"unit":"г"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Морковный салат с маслом';
UPDATE public.food_catalog SET ingredients = '[{"name":"свёкла","category":"vegetable","qty":100,"unit":"г"},{"name":"чеснок","category":"vegetable","qty":5,"unit":"г"},{"name":"масло растительное","category":"condiment","qty":10,"unit":"мл"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Свекольный салат';
UPDATE public.food_catalog SET ingredients = '[{"name":"яблоко","category":"fruit","qty":1,"unit":"шт"},{"name":"грецкие орехи","category":"other","qty":30,"unit":"г"}]' WHERE name = 'Яблоко + горсть орехов';
UPDATE public.food_catalog SET ingredients = '[{"name":"творог 9%","category":"dairy","qty":130,"unit":"г"},{"name":"мёд","category":"other","qty":20,"unit":"г"}]' WHERE name = 'Творог с мёдом';
UPDATE public.food_catalog SET ingredients = '[{"name":"банан","category":"fruit","qty":1,"unit":"шт"},{"name":"арахисовая паста","category":"other","qty":30,"unit":"г"}]' WHERE name = 'Банан + арахисовая паста';
UPDATE public.food_catalog SET ingredients = '[{"name":"кефир","category":"dairy","qty":200,"unit":"мл"},{"name":"огурцы","category":"vegetable","qty":60,"unit":"г"}]' WHERE name = 'Кефир с огурцом';
UPDATE public.food_catalog SET ingredients = '[{"name":"хлебцы","category":"grain","qty":40,"unit":"г"},{"name":"авокадо","category":"fruit","qty":0.5,"unit":"шт"},{"name":"соль","category":"condiment","qty":1,"unit":"щепотка"}]' WHERE name = 'Хлебцы с авокадо';
UPDATE public.food_catalog SET ingredients = '[{"name":"греческий йогурт","category":"dairy","qty":170,"unit":"г"},{"name":"ягоды","category":"fruit","qty":40,"unit":"г"}]' WHERE name = 'Греческий йогурт с ягодами';
UPDATE public.food_catalog SET ingredients = '[{"name":"сыр твёрдый","category":"dairy","qty":60,"unit":"г"},{"name":"виноград","category":"fruit","qty":50,"unit":"г"}]' WHERE name = 'Сыр + виноград';
